// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaEuLcrs21oas1ePTkuABcnWXaD4b-ItQ',
    appId: '1:958045292209:web:14a00fac964c3fafbe8490',
    messagingSenderId: '958045292209',
    projectId: 'schoolapp-eed9d',
    authDomain: 'schoolapp-eed9d.firebaseapp.com',
    storageBucket: 'schoolapp-eed9d.firebasestorage.app',
    measurementId: 'G-VEM8D87WJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyETM9Yqj0y_4PUxG9vNZ7BrLr91Lwgcw',
    appId: '1:958045292209:android:44f0b6b30d02c334be8490',
    messagingSenderId: '958045292209',
    projectId: 'schoolapp-eed9d',
    storageBucket: 'schoolapp-eed9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs3W8Eu7B-x3W-V9Hv4gsc5cD3KGpKLuM',
    appId: '1:958045292209:ios:a07279c52f3e7826be8490',
    messagingSenderId: '958045292209',
    projectId: 'schoolapp-eed9d',
    storageBucket: 'schoolapp-eed9d.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs3W8Eu7B-x3W-V9Hv4gsc5cD3KGpKLuM',
    appId: '1:958045292209:ios:a07279c52f3e7826be8490',
    messagingSenderId: '958045292209',
    projectId: 'schoolapp-eed9d',
    storageBucket: 'schoolapp-eed9d.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaEuLcrs21oas1ePTkuABcnWXaD4b-ItQ',
    appId: '1:958045292209:web:9c8b95bbfaaa15d0be8490',
    messagingSenderId: '958045292209',
    projectId: 'schoolapp-eed9d',
    authDomain: 'schoolapp-eed9d.firebaseapp.com',
    storageBucket: 'schoolapp-eed9d.firebasestorage.app',
    measurementId: 'G-FRL6NP2PDQ',
  );

}